### ISSUE TITLE
cannot find symbol Bundle

### ISSUE THREAD

**Issue by barrilocho** [zo0r/react-native-conekta#1]
Hello, I have this issue and other similar issues in Android Installation

/MainApplication.java:45: error: cannot find symbol
    protected void onCreate(Bundle savedInstanceState) {
                            ^
  symbol:   class Bundle
  location: class MainApplication

Any solution?
thank you

**Comment by zo0r** [comment]
@barrilocho I just updated the component to make it compatible with newest RN versions.
